export const products = [
  {
    id: 1,
    name: 'Black Canon Camera',
    price: 350,
    rating: 4.3,
    sold: 352,
    image: 'https://source.unsplash.com/W2Dta_Yiwfw',
  },
  {
    id: 2,
    name: 'White Wireless Earphone',
    price: 150,
    rating: 5.0,
    sold: 341,
    image: 'https://source.unsplash.com/SBLT7JohtCo',
  },
  {
    id: 3,
    name: 'Black Headset',
    price: 130,
    rating: 3.9,
    sold: 295,
    image: 'https://source.unsplash.com/dBwadhWa-lI',
  },
  {
    id: 4,
    name: 'Playstation 5',
    price: 500,
    rating: 4.5,
    sold: 288,
    image: 'https://source.unsplash.com/dUx0gwLbhzs',
  },
  {
    id: 5,
    name: 'White Keyboard',
    price: 200,
    rating: 5.0,
    sold: 196,
    image: 'https://source.unsplash.com/Ac9L5MrIPUQ',
  },
];
