export const users = [
  {
    id: 1,
    avatar: `https://randomuser.me/api/portraits/women/4.jpg`,
    name: 'Bealle Frankland',
    email: 'bealles-frankland@example.com',
    role: 'customer',
    status: 'active',
    created_at: 'November 07, 2020',
  },
  {
    id: 2,
    avatar: `https://randomuser.me/api/portraits/women/8.jpg`,
    name: 'Kelsi Kohrt',
    email: 'kelsi-kohrt@example.com',
    role: 'customer',
    status: 'active',
    created_at: 'November 02, 2020',
  },
  {
    id: 3,
    avatar: `https://randomuser.me/api/portraits/men/12.jpg`,
    name: 'Denny Marfell',
    email: 'denny-marfell@example.com',
    role: 'customer',
    status: 'active',
    created_at: 'October 31, 2020',
  },
  {
    id: 4,
    avatar: `https://randomuser.me/api/portraits/women/16.jpg`,
    name: 'Dede Iowarch',
    email: 'dede-iowarch@example.com',
    role: 'customer',
    status: 'active',
    created_at: 'October 31, 2020',
  },
  {
    id: 5,
    avatar: `https://randomuser.me/api/portraits/women/20.jpg`,
    name: 'Carmelia Bushill',
    email: 'carmelia-bushill@example.com',
    role: 'customer',
    status: 'active',
    created_at: 'October 24, 2020',
  },
  {
    id: 6,
    avatar: `https://randomuser.me/api/portraits/men/24.jpg`,
    name: 'Afton Maior',
    email: 'afton-maior@example.com',
    role: 'admin',
    status: 'active',
    created_at: 'October 16, 2020',
  },
  {
    id: 7,
    avatar: `https://randomuser.me/api/portraits/women/28.jpg`,
    name: 'Eula Issacson',
    email: 'eula-issacson@example.com',
    role: 'customer',
    status: 'active',
    created_at: 'September 29, 2020',
  },
  {
    id: 8,
    avatar: `https://randomuser.me/api/portraits/women/32.jpg`,
    name: 'Javier Blabber',
    email: 'javier-blabber@example.com',
    role: 'admin',
    status: 'active',
    created_at: 'September 29, 2020',
  },
  {
    id: 9,
    avatar: `https://randomuser.me/api/portraits/men/36.jpg`,
    name: 'Nikolaos Ciotto',
    email: 'nikolaos-ciotto@example.com',
    role: 'customer',
    status: 'active',
    created_at: 'September 15, 2020',
  },
  {
    id: 10,
    avatar: `https://randomuser.me/api/portraits/men/40.jpg`,
    name: 'Delbert McIlharga',
    email: 'delbert-mcilharga@example.com',
    role: 'customer',
    status: 'active',
    created_at: 'August 21, 2020',
  },
];

export const statuses = {
  active: 'green',
  inactive: 'red',
};
